django_yelp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='yelp_index', permanent=False)),
    path('admin/', admin.site.urls),
    path('yelpme/', include('yelp.urls')),
]

yelp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='yelp_index'),
    path('api/cuisine_autocomplete/', views.get_cuisine_autocomplete, name='cuisine_autocomplete'),
]

yelp/models.py
from django.db import models

# Create your models here.
class Cuisine(models.Model):
    label = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

yelp/forms.py
from django import forms

class CuisineForm(forms.Form):
    cuisine = forms.CharField(label="Cuisine:", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, 'placeholder': 'Enter Cuisine'}))

yelp/views.py
from django.shortcuts import render
from yelp.models import Cuisine
from django.http import HttpResponse
from yelp.forms import CuisineForm
from django_yelp import credentials

import requests
import json

AUTH_HEADER = {"Authorization":"Bearer {}".format(credentials.YELP_API_KEY)}

# Create your views here.
def index(request):
    if request.method == 'GET' and not request.GET.get('cuisine', ''):
        form = CuisineForm()
        return render(request, 'yelp/yelp.html', {'form': form})
    else:
        query = request.GET.get('cuisine', '')
        form = CuisineForm(initial={'cuisine': query})
        r = requests.get('https://api.yelp.com/v3/businesses/search', headers=AUTH_HEADER, params={'term': query,
                                                                                                    'categories': 'restaurants',
                                                                                                    'latitude': '37.786882',
                                                                                                    'longitude': '-122.399972'})
        businesses = []
        error = False
        if r.status_code == 200:
            api_data = r.json()
            if api_data['businesses']:
                businesses_unfiltered = api_data['businesses'][10:]
                for business in businesses_unfiltered:
                    temp = {}
                    temp['image_url'] = business.get('image_url', '')
                    temp['name'] = business.get('name', 'N/A')
                    temp['location'] = ' '.join(business['location'].get('display_address', 'N/A'))
                    temp['phone'] = business.get('display_phone', 'N/A')
                    temp['price'] = business.get('price', 'N/A')
                    temp['rating'] = business.get('rating', 'N/A')
                    businesses.append(temp)
                    del temp
            return render(request, 'yelp/yelp.html', {'form': form, 'query': query, 'businesses': businesses})
        else:
            error = True
            return render(request, 'yelp/yelp.html', {'form': form, 'error': error})



def get_cuisine_autocomplete(request):
    if request.is_ajax():
        term = request.GET.get('term', '')
        cuisines = Cuisine.objects.filter(name__contains=term)[:20]
        results = []
        for cuisine in cuisines:
            cuisine_json = {}
            cuisine_json['id'] = cuisine.id
            cuisine_json['label'] = cuisine.name
            cuisine_json['value'] = cuisine.name
            results.append(cuisine_json)
        data = json.dumps(results)
    else:
        data = 'ERROR'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Yelp Me</title>
    {% block styles %}{% endblock styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" type="text/css"/>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock scripts %}
</head>
<body>
    {%  block content %}{% endblock content %}
</body>
</html>

templates/yelp/yelp.html
{% extends "base.html" %}

{% block styles %}
    <style>
        .ui-autocomplete {
            position: absolute;
            z-index: 1000;
            cursor: default;
            padding: 0;
            margin-top: 2px;
            list-style: none;
            background-color: #ffffff;
            border: 1px solid #ccc
            -webkit-border-radius: 5px;
               -moz-border-radius: 5px;
                    border-radius: 5px;
            -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
               -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
                    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        }

        .ui-autocomplete > li {
            padding: 3px 20px;
        }

        .ui-autocomplete > li.ui-state-active {
          background-color: #dddddd;
        }

        .ui-helper-hidden-accessible {
          display: none;
        }

        .top-padding {
            padding-top: 2%;
        }
    </style>
{% endblock styles %}

{% block scripts %}
    <script>
        $(function() {
                $("#id_cuisine").autocomplete({
                    source: "api/cuisine_autocomplete/",
                    minLength: 2,
                });
        });
    </script>
{% endblock scripts %}

{% block content %}
    {% load dict_tags %}
    <div class="container top-padding">
        <form action="" method="get">
                <div class="form-group">
                    {{ form }}
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    {% if businesses %}
        <div class="container table-responsive top-padding">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Location</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Price</th>
                        <th scope="col">Rating</th>
                    </tr>
                </thead>
                <tbody>
                {% for business in businesses %}
                    <tr>
                        <td><img width=200px height=200px src="{{ business|get_item:"image_url" }}" class="img-thumbnail"></td>
                        <td>{{ business|get_item:"name" }}</td>
                        <td>{{ business|get_item:"location" }}</td>
                        <td>{{ business|get_item:"phone" }}</td>
                        <td>{{ business|get_item:"price" }}</td>
                        <td>{{ business|get_item:"rating" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

{% endblock content %}